window.EIKEN_EXAMPLES=window.EIKEN_EXAMPLES||{};
Object.assign(window.EIKEN_EXAMPLES,{
"virtuously":"She acted virtuously by returning the lost wallet with all the money still inside.",
"provident":"His provident habit of saving part of every paycheck helped him handle unexpected expenses.",
"rudimentary":"I have only a rudimentary knowledge of Spanish, enough to understand very simple phrases.",
"oblivious":"He was oblivious to the alarm because he was wearing noise-canceling headphones.",
"circumvent":"The company tried to circumvent the rule by finding a legal loophole.",
"deride":"It is cruel to deride someone for making a mistake in front of others.",
"incapacitate":"The severe back injury could incapacitate him for several weeks and prevent him from working.",
"rout":"The final game was a rout, with one team winning 8–0.",
"famine":"Years of drought caused a famine, leaving many families without enough food.",
"bunker":"The soldiers took shelter in an underground bunker during the air raid.",
"tidbit":"She shared an interesting tidbit about the actor that most fans did not know.",
"profusion":"The garden was filled with a profusion of flowers in every color.",
"conjecture":"Without evidence, the claim remains only conjecture rather than a proven fact.",
"provocation":"His insult was a deliberate provocation intended to make his opponent angry.",
"leeway":"The teacher gave us some leeway on the deadline, allowing us to submit the assignment a day late.",
"reminisce":"Whenever they meet, the old friends reminisce about their school days.",
"rectify":"The bank apologized and rectified the error by returning the missing money.",
"advocate":"Many doctors advocate regular exercise because it improves long-term health.",
"amplify":"A microphone can amplify a quiet voice so everyone in the hall can hear it.",
"contrived":"Their conversation sounded contrived because every line felt planned instead of natural.",
"jaded":"After working in luxury hotels for years, he became jaded and was no longer impressed by expensive rooms.",
"molded":"Years of strict training molded her into a disciplined athlete.",
"shrouded":"The mountain was shrouded in thick fog, hiding the peak from view.",
"ravenous":"After hiking all day without lunch, I was ravenous and ate two full meals.",
"subsidiary":"The electronics company opened a subsidiary in Korea that is owned by the parent company.",
"dexterous":"The dexterous surgeon moved the tiny instruments with remarkable skill and control.",
"probationary":"During her three-month probationary period, the company evaluated whether she was suitable for the permanent job.",
"aficionado":"He is a jazz aficionado who owns hundreds of records and knows the history of every major artist.",
"mourner":"Each mourner placed a flower beside the coffin to honor the person who had died.",
"culprit":"The muddy dog was the culprit that had knocked over the trash can.",
"tycoon":"The hotel tycoon owns luxury properties in cities around the world.",
"infamy":"The dictator achieved infamy because of the terrible crimes committed under his rule.",
"eccentricity":"One of his eccentricities is wearing a winter coat even in the middle of summer.",
"sustenance":"For the stranded hikers, a few energy bars provided enough sustenance to keep them going.",
"magnitude":"Only after seeing the destroyed buildings did we understand the magnitude of the earthquake.",
"resuscitate":"Paramedics managed to resuscitate the man after his heart had stopped.",
"curtail":"The school introduced new rules to curtail bullying and reduce the number of incidents.",
"invoke":"The lawyer invoked a constitutional right to protect her client from being forced to testify.",
"conjure":"The smell of fresh bread can conjure memories of childhood for many people.",
"annexing":"The country was accused of annexing neighboring territory and adding it to its own land.",
"thwarting":"The locked gate was thwarting our attempt to enter the building.",
"pilfering":"The employee was caught pilfering small amounts of cash from the register every week.",
"hijacking":"The police stopped an attempted hijacking before the attackers could take control of the aircraft.",
"fruition":"After ten years of planning, the research center finally came to fruition and opened its doors.",
"deference":"Out of deference to the elderly guest, everyone allowed her to speak first.",
"audacity":"He had the audacity to demand a raise after arriving late almost every day.",
"dismissal":"Repeated dishonesty eventually led to his dismissal from the company.",
"fiendish":"The villain created a fiendish plan designed to cause as much suffering as possible.",
"forsaken":"The old village looked forsaken, with empty houses and no people in sight.",
"apathetic":"Many voters seemed apathetic and showed little interest in the election.",
"ardent":"She is an ardent supporter of animal welfare and volunteers at a shelter every weekend.",
"wayward":"The wayward teenager repeatedly ignored rules and often disappeared from home without permission.",
"fraught":"The negotiations were fraught with tension, and every small disagreement threatened to end the talks.",
"benign":"The doctor explained that the tumor was benign and would not spread to other parts of the body.",
"frigid":"We stepped outside into frigid air that was well below freezing.",
"check up on":"I called my grandmother to check up on her and make sure she was feeling better.",
"wriggle out of":"He tried to wriggle out of paying his share by pretending he had forgotten his wallet.",
"suck up to":"He keeps sucking up to the boss by praising everything she says.",
"chip away at":"If you chip away at the assignment for thirty minutes each day, it will eventually be finished.",
"kick in":"The pain medicine should kick in within twenty minutes and start reducing the pain.",
"drift off":"The quiet music helped me drift off and fall asleep.",
"horn in":"He kept trying to horn in on our private conversation even though nobody had invited him.",
"went at":"The two boxers went at each other aggressively from the opening bell.",
"bore with":"She bore with the noisy construction for months without complaining.",
"mopped up":"After the party, we mopped up the spilled drinks and cleaned the kitchen.",
"nailed down":"We finally nailed down the travel dates, so the schedule is now definite.",
"whip up":"I can whip up a simple pasta dinner in about fifteen minutes.",
"scratch out":"He scratched out the wrong address and wrote the correct one above it.",
"tap into":"The company hopes to tap into the growing demand for affordable electric cars.",
"root for":"Even though my team was losing, I continued to root for them until the final whistle.",
"consolidated":"The company consolidated three small offices into one larger headquarters.",
"equivocated":"When asked whether taxes would rise, the candidate equivocated and avoided giving a clear answer.",
"alleviated":"The ice pack alleviated the swelling and made the injury less painful.",
"emanated":"A strong smell of smoke emanated from the kitchen and spread through the house.",
"mutter":"He began to mutter under his breath so quietly that I could barely hear him.",
"bolster":"The new evidence helped bolster her argument by giving it stronger support.",
"spar":"The two boxers sparred lightly in practice without trying to hurt each other.",
"defer":"We decided to defer the decision until next week so we could gather more information.",
"solicit":"The charity sent letters to solicit donations from local businesses.",
"dissipate":"The morning mist began to dissipate as the sun warmed the valley.",
"torments":"The memories of the accident still torment him and make it difficult to sleep.",
"buskers":"Buskers played guitar and violin on the street while passersby dropped coins into their cases.",
"vestiges":"Only a few stone walls remain as vestiges of the ancient castle.",
"envoys":"The president sent envoys to the neighboring country to negotiate a peace agreement.",
"stooge":"He was treated like a stooge, carrying out orders for a powerful man without making decisions himself.",
"extraterrestrial":"Scientists continue to search for signs of extraterrestrial life beyond Earth.",
"incumbent":"The incumbent mayor is running for another term after four years in office.",
"pilgrim":"The pilgrim walked hundreds of kilometers to reach the sacred temple.",
"inherent":"Risk is inherent in mountain climbing because danger is naturally part of the activity.",
"eccentric":"The eccentric professor wore mismatched shoes and kept a parrot in his office.",
"auspicious":"Clear skies on the wedding morning were considered an auspicious sign for the couple's future.",
"ornate":"The palace had ornate ceilings covered with gold patterns and detailed paintings.",
"pertinent":"Please include only information pertinent to the case and leave out unrelated details.",
"contrite":"He looked genuinely contrite after hurting his friend and apologized sincerely.",
"dubious":"I was dubious about the offer because it promised huge profits with almost no risk.",
"lucrative":"The software business became highly lucrative and earned millions of dollars each year.",
"obliterated":"The explosion obliterated the small building, leaving almost nothing standing.",
"concocted":"He concocted an elaborate excuse about a broken train, but nobody believed the story.",
"acclimated":"After a few weeks, she acclimated to the hot climate and no longer felt uncomfortable outside.",
"deduced":"From the wet umbrella by the door, I deduced that it had been raining.",
"queasy":"The rough boat ride made me feel queasy, as if I might be sick.",
"staunch":"She remained a staunch supporter of the team even during its worst seasons.",
"porous":"The sponge is porous, so water can pass through its many tiny holes.",
"scruffy":"He arrived at the interview looking scruffy, with wrinkled clothes and uncombed hair.",
"ditch":"The car slid off the road and ended up in a deep ditch beside the highway.",
"gist":"I did not understand every word, but I understood the gist of the conversation.",
"omen":"Dark clouds were an omen of the storm that arrived later that afternoon.",
"loot":"Police recovered stolen loot, including jewelry and cash, from the thieves' apartment.",
"sentiment":"Public sentiment turned against the proposal after several problems were reported.",
"dearth":"There is a dearth of affordable housing, so many families cannot find a place they can pay for.",
"entailed":"The new job entailed frequent travel, meaning she had to fly abroad almost every week.",
"mulled":"He mulled the offer for several days before deciding whether to accept it.",
"averted":"The pilot's quick reaction averted a disaster and prevented the two aircraft from colliding.",
"alacrity":"She accepted the new assignment with alacrity, starting immediately and with obvious enthusiasm.",
"prevarication":"His constant prevarication made it difficult to get a straight answer from him.",
"convergence":"The convergence of the two roads creates heavy traffic where they meet.",
"nostalgia":"Seeing his old school filled him with nostalgia and memories of childhood.",
"flouted":"The company openly flouted the safety rules and continued operating despite repeated warnings.",
"deified":"Fans practically deified the singer, treating her as if she could do no wrong.",
"fermented":"The cabbage was fermented for several days, allowing bacteria to create its sour flavor.",
"coaxed":"She coaxed the frightened cat out from under the bed by offering it food.",
"pungent":"The pungent smell of garlic was so strong that it filled the entire kitchen.",
"ambivalent":"I feel ambivalent about moving abroad because I am excited about the opportunity but sad to leave my family.",
"lustrous":"Her hair looked lustrous under the light, smooth and beautifully shiny.",
"boisterous":"The boisterous children ran around the room shouting and laughing loudly.",
"disheveled":"He woke up late and arrived with disheveled hair and a wrinkled shirt.",
"incisive":"Her incisive question immediately exposed the weakest part of the argument.",
"suave":"The suave host greeted every guest with polished manners and effortless charm.",
"perennial":"Traffic congestion is a perennial problem in the city, returning year after year."
});