window.EIKEN_EXAMPLES=window.EIKEN_EXAMPLES||{};
Object.assign(window.EIKEN_EXAMPLES,{
"peripheral":"The argument focused on a peripheral issue that was not central to the main problem.",
"maternal":"Her maternal instinct made her comfort the frightened child like a caring mother.",
"erratic":"His driving was erratic, suddenly speeding up, slowing down, and changing lanes without warning.",
"menacing":"The stranger gave us a menacing look that made us feel threatened.",
"equitable":"The judge tried to reach an equitable decision that treated both sides fairly.",
"taint":"One cheating scandal can taint an athlete's reputation for years.",
"jilt":"She feared he would jilt her and end their relationship just before the wedding.",
"scour":"Police scoured the forest for hours, searching every path for the missing child.",
"quell":"The coach spoke calmly to quell the argument before it turned into a fight.",
"poise":"Even under intense pressure, she kept her poise and answered calmly.",
"loam":"The farmer planted vegetables in the rich loam because the fertile soil held water well.",
"crux":"The crux of the problem is simple: we do not have enough money to finish the project.",
"ward":"After surgery, the patient was moved to a quiet hospital ward to recover.",
"weigh in":"Several experts were invited to weigh in and give their opinions on the proposal.",
"scrub up":"Before entering the operating room, the surgeon had to scrub up and wash her hands thoroughly.",
"black out":"He stood up too quickly, felt dizzy, and nearly blacked out.",
"crouch down":"She crouched down behind the wall so nobody could see her.",
"hang on":"Hang on for a minute while I find the document you asked for.",
"while away":"We whiled away the rainy afternoon by playing cards and talking.",
"zip up":"Zip up your jacket before going outside because it is freezing.",
"shell out":"I had to shell out $300 for an emergency car repair.",
"snap at":"He was stressed and snapped at his friend even though she had done nothing wrong.",
"carve out":"She managed to carve out an hour each morning for exercise despite her busy schedule.",
"descend on":"Hundreds of tourists descend on the small town every summer, filling its streets and hotels.",
"lay up":"His knee injury laid him up for two weeks, so he had to stay home and rest.",
"clam up":"Whenever the police asked about the accident, he would clam up and refuse to speak.",
"fend off":"She used an umbrella to fend off the attacking dog and keep it away.",
"run over":"Let's run over the main points once more before the test.",
"fly into":"When he discovered the broken window, he flew into a rage and started shouting.",
"backlog":"The office has a backlog of unanswered emails because staff have been short-handed all week.",
"upheaval":"The sudden change of government caused months of political upheaval and uncertainty.",
"outreach":"The charity's outreach program brings food and medical help directly to homeless people.",
"hindsight":"In hindsight, buying the cheapest car was a mistake because repairs cost more than we saved.",
"appeased":"The angry customer was appeased after the store offered a full refund and an apology.",
"expounded":"The professor expounded on the theory for an hour, explaining it in great detail.",
"peddled":"Street vendors peddled fruit and souvenirs to tourists along the busy road.",
"rescinded":"The company rescinded the job offer after discovering false information on the application.",
"grime":"Years of grime covered the old window, making the glass look almost black.",
"ridge":"We climbed along the narrow mountain ridge with steep drops on both sides.",
"glaze":"The baker brushed a sweet glaze over the cake, giving it a shiny surface.",
"niche":"The company found a profitable niche by selling equipment only for left-handed musicians.",
"posterity":"The diary was preserved for posterity so future generations could understand life during the war.",
"quarantine":"The sick dog was kept in quarantine so it would not infect the other animals.",
"tempest":"A violent tempest hit the coast, bringing fierce winds and heavy rain.",
"saturation":"The market has reached saturation because almost everyone who wants a smartphone already owns one.",
"incursion":"The army responded quickly to the enemy's incursion across the border.",
"grievance":"The employee filed a formal grievance after repeatedly being denied overtime pay.",
"enigma":"The disappearance remains an enigma because nobody knows what happened or why.",
"query":"I sent the company a query asking whether the product was still under warranty.",
"fastidious":"She is fastidious about cleanliness and notices even a tiny speck of dust.",
"exuberant":"The fans were exuberant after the victory, cheering, singing, and jumping with excitement.",
"unassuming":"Despite being a famous scientist, he was unassuming and never boasted about his achievements.",
"anonymous":"The donor wished to remain anonymous, so no one was told his name.",
"brusquely":"The busy clerk answered brusquely, giving a short and unfriendly reply.",
"surreptitiously":"He surreptitiously checked his phone under the desk so the teacher would not notice.",
"cordially":"The two rivals greeted each other cordially, smiling and shaking hands warmly.",
"ploddingly":"The exhausted hikers moved ploddingly up the hill, taking slow and heavy steps.",
"impasse":"The negotiations reached an impasse because neither side was willing to compromise.",
"contempt":"She looked at the dishonest official with contempt because she had no respect for him.",
"jeopardy":"Missing another payment could put the family's home in jeopardy.",
"futility":"After trying the broken key ten times, he finally accepted the futility of continuing.",
"plantations":"Large tea plantations covered the hills, with rows of tea bushes stretching for miles.",
"sockets":"There were not enough electrical sockets in the room to plug in all our devices.",
"provisions":"The hikers packed enough provisions, including food and water, for three days in the mountains.",
"ventures":"Her first two business ventures failed, but her third company became successful.",
"percolated":"News of the decision slowly percolated through the office as employees told one another.",
"contorted":"His face contorted in pain when the doctor touched his injured ankle.",
"tarnished":"The silver necklace had tarnished and lost its bright shine.",
"appraised":"The jeweler appraised the ring at $5,000 after carefully examining its diamond.",
"buttress":"Extra steel beams were added to buttress the weak roof and keep it from collapsing.",
"cajole":"She managed to cajole her brother into helping by praising him and promising him dessert.",
"redeem":"He worked hard to redeem himself after the mistake and regain everyone's trust.",
"gratify":"Winning the award gratified her because it showed that people valued her work.",
"translucent":"The bathroom window was translucent, allowing light through but preventing people from seeing inside clearly.",
"fortuitous":"Our fortuitous meeting at the airport was a lucky coincidence neither of us had planned.",
"inane":"The interview was filled with inane questions that were silly and had no real value.",
"pampered":"The pampered child was used to getting every toy he asked for.",
"scamper":"The children scampered across the playground, running quickly in small excited steps.",
"wrest":"The rebels tried to wrest control of the city from the government by force.",
"peek":"She took a quick peek inside the box before wrapping the gift.",
"belittle":"A good manager should not belittle employees by making them feel stupid or unimportant.",
"rotund":"The rotund cat had a very round body and waddled when it walked.",
"malevolent":"The villain had a malevolent plan to hurt innocent people simply out of hatred.",
"ascetic":"The monk lived an ascetic life with few possessions, simple food, and no luxuries.",
"tacit":"Their silence was taken as tacit approval, even though nobody said yes directly.",
"vertical":"The ladder was almost vertical, standing straight up against the wall.",
"intangible":"Trust is intangible: you cannot touch it, but it is essential in a relationship.",
"squeamish":"He is squeamish about blood and feels sick whenever he sees a serious injury.",
"enraptured":"The children were enraptured by the magician and watched every trick in complete fascination.",
"lanky":"The lanky teenager was very tall and thin, with long arms and legs.",
"vivacious":"Her vivacious personality filled the room because she was lively, cheerful, and energetic.",
"mutinous":"The mutinous sailors refused to obey the captain and threatened to take control of the ship.",
"dilapidated":"The dilapidated house had broken windows, a leaking roof, and walls that were falling apart.",
"caustic":"His caustic remark was so harsh and insulting that the whole room became silent.",
"ticklish":"Negotiating salaries is a ticklish issue because even a small mistake can upset employees.",
"subversive":"The government banned the newspaper, claiming that its articles were subversive and encouraged people to overthrow the regime.",
"repulsed":"She was repulsed by the rotten smell and immediately stepped away.",
"extolled":"The coach extolled the player's dedication, praising his hard work in front of the whole team.",
"conciliated":"The manager conciliated the angry customer by apologizing and offering a refund.",
"bungled":"The company bungled the launch by sending the wrong product to thousands of customers.",
"nod off":"I started to nod off during the late-night lecture because I could barely keep my eyes open.",
"pipe down":"The teacher told the noisy students to pipe down and be quiet.",
"drone on":"The speaker droned on for an hour in the same dull voice, and several people fell asleep.",
"crank out":"The factory can crank out thousands of bottles every hour.",
"tail off":"Sales were strong in June but began to tail off gradually during July.",
"patch up":"The brothers finally patched up their relationship and became friends again.",
"choke off":"The sanctions were designed to choke off the flow of money to the armed group.",
"own up":"He finally owned up to breaking the window and admitted that it was his fault.",
"hush up":"The company tried to hush up the accident so the public would not hear about it.",
"get behind":"Most employees got behind the new plan and actively supported it.",
"plug in":"Plug in the charger before your phone battery runs out.",
"farm out":"The company decided to farm out its customer support to an outside firm.",
"sit by":"I could not just sit by and watch someone being bullied without helping.",
"dive in":"We had very little time, so everyone dived in and started working immediately.",
"strike back":"After being attacked, the army struck back with a counterattack the next morning.",
"pan out":"We were unsure about the business idea, but it panned out and became highly successful.",
"garnish":"The chef garnished the soup with fresh herbs to make it look more attractive.",
"cramp":"A painful cramp suddenly tightened the muscle in my leg during the race.",
"disciple":"He became a disciple of the famous teacher and devoted himself to learning her ideas.",
"glitch":"A small software glitch caused the app to freeze for a few seconds.",
"sedentary":"A sedentary lifestyle involves sitting for long periods and getting very little exercise.",
"profane":"Many worshippers considered his rude joke inside the temple profane and disrespectful to something sacred.",
"categorical":"She gave a categorical refusal, making it completely clear that the answer was no.",
"incensed":"Residents were incensed when they learned the city planned to double their taxes.",
"shard":"A sharp shard of broken glass was lying on the kitchen floor.",
"forgery":"The painting looked authentic, but experts later proved that it was a forgery.",
"chuckle":"He gave a quiet chuckle when he noticed the small joke hidden in the message.",
"hardship":"Losing both his job and home caused severe hardship for the entire family.",
"antecedent":"The telegraph was an important antecedent of modern instant messaging because it allowed rapid long-distance communication.",
"annulment":"The court granted an annulment, legally declaring that the marriage was no longer valid.",
"overture":"The company made an overture to its rival by proposing that the two firms cooperate.",
"ferocious":"The ferocious dog bared its teeth and charged at anyone who came near.",
"emblematic":"The cherry blossom is emblematic of spring in Japan and is strongly associated with the season.",
"rampant":"Corruption was rampant in the department, with dishonest behavior occurring everywhere.",
"humdrum":"He quit his humdrum office job because doing the same routine every day bored him.",
"gauche":"His gauche joke about money at the funeral made everyone uncomfortable.",
"esoteric":"The lecture was so esoteric that only specialists in advanced physics could understand it.",
"ruthless":"The ruthless dictator imprisoned anyone who challenged his power and showed no mercy.",
"despondent":"She became despondent after failing the exam twice and felt that nothing would improve.",
"indistinct":"The voice on the old recording was indistinct, so I could not clearly understand the words.",
"cliquish":"The group was cliquish and rarely welcomed anyone outside its small circle of friends.",
"shrill":"A shrill alarm produced such a high, piercing sound that everyone covered their ears.",
"lurid":"The newspaper used lurid headlines about blood and violence to shock readers.",
"hampered":"Heavy snow hampered rescue efforts by making the mountain roads almost impossible to use.",
"galvanized":"The shocking report galvanized the community into action, and hundreds volunteered to help.",
"abducted":"The child was abducted from the street and taken away against his will.",
"demonized":"The politician was demonized by his opponents, who portrayed him as entirely evil.",
"vanquishing":"The army celebrated vanquishing its enemy after winning the decisive final battle.",
"consorting":"He was criticized for consorting with known criminals and spending time in their company.",
"tampering":"Police found evidence of tampering with the security camera, suggesting someone had deliberately altered it."
});