window.EIKEN_EXAMPLES=window.EIKEN_EXAMPLES||{};
Object.assign(window.EIKEN_EXAMPLES,{
"antagonizing":"His constant mocking was antagonizing his teammates and making them increasingly angry with him.",
"marginally":"The new model is only marginally faster, improving performance by just a few percent.",
"judiciously":"She spent the limited budget judiciously, choosing only the most necessary items.",
"preemptively":"The company recalled the product preemptively before any customers were injured.",
"delirious":"With a very high fever, the patient became delirious and started saying things that made no sense.",
"contentious":"The proposal was highly contentious, causing heated arguments between the two sides.",
"droopy":"The plant looked droopy because its leaves were hanging down from lack of water.",
"austere":"The monk lived in an austere room with only a bed, a desk, and no decorations.",
"connoisseurs":"Wine connoisseurs can often identify a region or grape variety just from the taste.",
"beneficiaries":"Students from low-income families are the main beneficiaries of the new scholarship program.",
"procrastinators":"Procrastinators often wait until the final night to begin work that was assigned weeks earlier.",
"renegades":"The renegades abandoned their former group and began fighting against it.",
"abating":"The wind is finally abating, becoming weaker as the storm moves away.",
"swilling":"He was swilling beer straight from the bottle, drinking large amounts very quickly.",
"retorting":"She kept retorting with sharp answers whenever anyone criticized her.",
"lurking":"A cat was lurking under the car, hidden and waiting quietly for a bird.",
"untenable":"His explanation became untenable once the video clearly showed that he was lying.",
"venomous":"The snake is venomous, and its bite can inject a dangerous toxin.",
"malleable":"Warm clay is malleable, so it can easily be shaped by hand.",
"ecstatic":"She was ecstatic after receiving her acceptance letter and could not stop smiling.",
"budge":"The heavy cabinet would not budge even when three people pushed it.",
"forgo":"He decided to forgo dessert so he could reduce his sugar intake.",
"lament":"Many residents lament the loss of the old park, saying the neighborhood no longer feels the same.",
"usurp":"The general tried to usurp the king's power and take control of the country for himself.",
"insurmountable":"At first the debt seemed insurmountable, but a careful repayment plan made it manageable.",
"bedraggled":"After walking through the storm without an umbrella, she looked bedraggled, wet, and exhausted.",
"derided":"The idea was derided as ridiculous at first, but years later it became widely accepted.",
"nonchalant":"He acted nonchalant about the exam results, as if he did not care at all.",
"gratuity":"A 15 percent gratuity was added to the restaurant bill as a tip for the staff.",
"hallmark":"Careful attention to detail is a hallmark of her work and appears in everything she produces.",
"specimen":"The scientist examined a blood specimen under the microscope.",
"deterrent":"The threat of a large fine can be a strong deterrent against illegal parking.",
"hatch":"The chicks began to hatch, breaking through their eggshells one by one.",
"glut":"A glut of unsold apartments caused prices to fall because supply greatly exceeded demand.",
"whim":"He bought a plane ticket on a whim, making the decision suddenly with no planning.",
"thesis":"Her thesis argues that social media has changed how young people form political opinions.",
"crack up":"The comedian's impression made the whole audience crack up with laughter.",
"dash off":"I had to dash off a quick email before leaving for the airport.",
"fall through":"Our vacation plans fell through when the airline canceled every flight.",
"peter out":"The applause slowly petered out until the room became completely quiet.",
"butting in":"He kept butting in while others were speaking, interrupting them before they could finish.",
"clamming up":"The suspect was talking freely until the detective mentioned the stolen money; then he started clamming up.",
"facing off":"The two champions are facing off in the final match tonight.",
"knuckling down":"With only a month left before the exam, she is finally knuckling down and studying every day.",
"act up":"My old laptop has started to act up, freezing and shutting down without warning.",
"stand in":"The assistant will stand in for the manager while she is away.",
"level off":"After rising for several months, housing prices began to level off and remain stable.",
"lash out at":"He lashed out at his brother in anger, shouting insults that he later regretted.",
"make off with":"The thief made off with the woman's handbag and disappeared into the crowd.",
"put in for":"She put in for two weeks of vacation and is waiting for her manager's approval.",
"gang up on":"Several students ganged up on the new boy, teasing him together until a teacher intervened.",
"hurl":"The angry fan hurled a bottle toward the field, throwing it with great force.",
"berate":"The coach berated the players after the loss, angrily criticizing their lack of effort.",
"stifle":"Fear of criticism can stifle creativity by making people afraid to share new ideas.",
"yield":"The experiment yielded useful results that helped answer the researchers' main question.",
"vulgar":"His vulgar joke was rude and inappropriate for a formal dinner.",
"docile":"The horse was surprisingly docile and calmly followed every command.",
"eclectic":"Her playlist is eclectic, mixing jazz, hip-hop, classical music, and rock.",
"frenetic":"The final hour before the deadline was frenetic, with everyone rushing around and working at top speed.",
"ventilated":"We ventilated the room by opening all the windows to let fresh air circulate.",
"placated":"The angry passenger was placated after the airline upgraded his seat and apologized.",
"vacillated":"She vacillated between studying law and medicine, changing her mind several times.",
"pulsated":"The lights pulsated with the music, growing brighter and dimmer in a steady rhythm.",
"upholstering":"She is upholstering the old chair with new fabric to replace the torn covering.",
"upstaging":"The supporting actor was accused of upstaging the star by drawing all the audience's attention.",
"extinguishing":"Firefighters spent hours extinguishing the warehouse fire until no flames remained.",
"extorting":"The gang was arrested for extorting money from shop owners by threatening them.",
"fishy":"His story sounded fishy because the details kept changing every time he told it.",
"dainty":"She served dainty sandwiches that were small, delicate, and carefully arranged.",
"irate":"The irate customer demanded to speak to the manager after being charged twice.",
"doleful":"He gave a doleful sigh and stared sadly at the empty seat beside him.",
"impertinent":"The employee's impertinent remark to the director was disrespectful and rude.",
"analogous":"A computer's memory is sometimes described as analogous to a human brain's ability to store information.",
"adverse":"The medicine can have adverse effects, including nausea and dizziness.",
"surmised":"From the muddy footprints, the detective surmised that someone had entered through the garden.",
"epitomized":"Her calm response during the crisis epitomized the professionalism expected from a leader.",
"ascribed":"The sudden sales increase was ascribed to the company's successful advertising campaign.",
"contravened":"The factory contravened environmental regulations by dumping waste into the river.",
"propelled":"A strong tailwind propelled the boat forward much faster than expected.",
"imbued":"The speech was imbued with hope, leaving the audience feeling optimistic about the future.",
"embellished":"He embellished the story by adding dramatic details that had never actually happened.",
"resonated":"Her message about loneliness resonated with many listeners because they had felt the same way.",
"indecently":"The performer was accused of behaving indecently in public and was removed from the venue.",
"impetuously":"He impetuously quit his job during an argument without thinking about what he would do next.",
"hospitably":"They welcomed us hospitably, offering food, drinks, and a comfortable place to sleep.",
"arguably":"This is arguably the city's best museum, although reasonable people may disagree.",
"demise":"The rise of smartphones contributed to the demise of many small camera companies.",
"prowess":"Her mathematical prowess was obvious when she solved the difficult problem in seconds.",
"fanfare":"The product was launched with great fanfare, including speeches, fireworks, and heavy publicity.",
"tenacity":"His tenacity kept him training for years despite repeated injuries and defeats.",
"artillery":"Heavy artillery fired large shells from several kilometers behind the front line.",
"impulse":"On impulse, she bought the expensive shoes even though she had not planned to shop.",
"embargo":"The country imposed an oil embargo, refusing to sell oil to its rival.",
"uprising":"The uprising began when thousands of citizens took to the streets against the government.",
"incoherent":"After the accident, he was confused and gave an incoherent explanation that nobody could follow.",
"insipid":"The soup was insipid because it had almost no flavor or seasoning.",
"innocuous":"The spider looks frightening, but it is actually innocuous and cannot harm people.",
"interim":"An interim manager will run the department temporarily until a permanent replacement is hired.",
"facetious":"His facetious comment was meant as a joke, but everyone took it seriously.",
"somber":"The mood at the memorial was somber, with people speaking quietly and looking sad.",
"cramped":"Four adults shared the cramped room, which barely had enough space for two beds.",
"hulking":"A hulking security guard stood by the door, enormous and powerfully built.",
"plumb":"The builder checked that the wall was plumb and perfectly vertical before continuing.",
"savvy":"She is financially savvy and understands how to invest, save, and avoid unnecessary fees.",
"pallid":"After being sick for several days, his face looked pallid and unusually pale.",
"savory":"The kitchen was filled with the savory smell of roasted meat and herbs.",
"uproars":"The controversial decisions caused uproars, with angry crowds shouting in protest.",
"consternations":"The sudden announcement caused consternation among employees, who were shocked and worried about their jobs.",
"ambushes":"The soldiers avoided narrow valleys because they were ideal places for enemy ambushes.",
"annotations":"Her textbook was full of annotations, with notes written beside nearly every paragraph.",
"elucidated":"The professor elucidated the theory by giving a simple example everyone could understand.",
"venerated":"The elderly doctor was venerated in the village because generations of families respected and admired him.",
"eclipsed":"The younger athlete eclipsed the previous champion by breaking all of her records.",
"stuttered":"He stuttered nervously during the interview, repeating the first sounds of several words.",
"capitulated":"After weeks of resistance, the company capitulated and accepted all of the union's demands.",
"stagnated":"The economy stagnated for years, showing almost no growth or improvement.",
"abridged":"I read an abridged version of the novel that was shortened to half its original length.",
"bastions":"The universities became bastions of free debate, places where open discussion was strongly protected.",
"bouts":"She suffers occasional bouts of severe headaches that last for several hours.",
"edicts":"The ruler issued strict edicts ordering citizens to obey the new laws.",
"outings":"The school organizes weekend outings to museums, parks, and historical sites.",
"hailed from":"Although she works in Tokyo now, she originally hailed from a small town in Hokkaido.",
"launched into":"As soon as the meeting began, he launched into a long complaint about the budget.",
"detracted from":"The poor sound quality detracted from the concert and made it less enjoyable.",
"roped in":"I was roped in to help with the event even though I had not planned to volunteer.",
"penciling in":"I'm penciling in a meeting for Tuesday, but we can change the time later if necessary.",
"boxing in":"Parking trucks on both sides of the driveway was boxing in my car and making it impossible to leave.",
"stooping to":"He was shocked that his rival was stooping to personal insults instead of discussing the issue.",
"palming off":"The shop was caught palming off cheap copies as genuine designer bags.",
"pine for":"After moving abroad, she began to pine for her hometown and missed it deeply.",
"vouch for":"I can vouch for his honesty because I have worked with him for ten years.",
"dawn on":"It suddenly dawned on me that I had left my passport at home.",
"stock up on":"Before the typhoon, families stocked up on bottled water and canned food.",
"leap out at":"The bright red warning sign leaped out at me as soon as I entered the room.",
"worm out of":"He tried to worm out of washing the dishes by pretending he had homework.",
"belly up to":"The customers bellied up to the bar and ordered drinks from the bartender.",
"felony":"Armed robbery is a felony and can lead to a long prison sentence.",
"pageant":"The town held a colorful historical pageant with costumes, music, and a large parade.",
"convulsion":"The child had a sudden convulsion, with his body shaking uncontrollably for several seconds.",
"diversion":"Watching a funny movie was a welcome diversion from the stress of studying.",
"encumbered":"She was encumbered by two heavy suitcases and could barely climb the stairs.",
"berated":"The supervisor berated him for arriving late, angrily criticizing him in front of everyone.",
"patronized":"She felt patronized when the salesman spoke to her as if she were a child.",
"tapered":"The road tapered from four lanes to two as it approached the mountain.",
"frisked":"Security officers frisked the suspect, checking his clothing for hidden weapons.",
"regurgitated":"Instead of explaining the concept, he simply regurgitated the textbook word for word.",
"dissipated":"The morning fog dissipated after sunrise and gradually disappeared.",
"vibrantly":"The market was vibrantly decorated with bright flags, flowers, and colorful lights.",
"fraudulently":"He fraudulently claimed insurance money by pretending that his car had been stolen.",
"enviously":"She looked enviously at her friend's new apartment because she wished she had one like it."
});