window.EIKEN_EXAMPLES=window.EIKEN_EXAMPLES||{};
Object.assign(window.EIKEN_EXAMPLES,{
"mitigate":"Planting more trees can mitigate summer heat by providing shade and cooling the air.",
"lucid":"Her lucid explanation made the difficult idea easy for everyone to understand.",
"appease":"He offered a refund to appease the angry customer and calm the situation.",
"embezzlement":"The accountant was arrested for embezzlement after secretly taking company money for years.",
"notoriety":"The scandal gave the politician notoriety, making him famous for all the wrong reasons.",
"fortitude":"She showed great fortitude by continuing the race despite the pain in her injured leg.",
"cessation":"The doctor advised a complete cessation of smoking, meaning he should stop entirely.",
"clatter":"A loud clatter came from the kitchen as several metal pans fell onto the floor.",
"acclaim":"The film received worldwide acclaim because critics and audiences praised it highly.",
"bigotry":"His bigotry was clear when he refused to hire people simply because of their religion.",
"dogma":"The group treated its leader's ideas as dogma and refused to question them.",
"gaunt":"After weeks without enough food, the prisoner looked gaunt, with a thin face and hollow cheeks.",
"meager":"The family survived on a meager income that barely covered food and rent.",
"rife":"Rumors were rife throughout the school, and almost everyone had heard a different story.",
"virile":"The actor was often cast as a virile hero because of his strong, energetic appearance.",
"invigorated":"After a short swim, she felt invigorated and full of energy again.",
"provincial":"He left the small provincial town and moved to the capital for more opportunities.",
"contiguous":"The two farms are contiguous, sharing a long boundary with no land between them.",
"tenuous":"The evidence against him was tenuous, based on only one weak and unreliable witness.",
"collate":"Please collate the survey results into one organized report before the meeting.",
"revoke":"The agency may revoke your license if you repeatedly break the safety rules.",
"bemoan":"Instead of bemoaning his bad luck, he decided to work on solving the problem.",
"thwart":"Security guards managed to thwart the robbery before the thieves entered the bank.",
"paramount":"Patient safety is paramount in a hospital and must come before convenience.",
"haphazard":"Books were piled in a haphazard way, with no order or system at all.",
"pristine":"The beach was pristine, with clear water and no trash anywhere.",
"heedless":"He was heedless of the warning signs and walked straight into the dangerous area.",
"implored":"She implored the doctor to save her dog, begging him not to give up.",
"purged":"The new manager purged the department of corrupt employees and removed them all.",
"reverted":"When the new system failed, the company reverted to its old method.",
"grafted":"The gardener grafted a branch from one apple tree onto another tree.",
"demeanor":"Despite the tense interview, her calm demeanor made her appear confident and relaxed.",
"discretion":"The teacher used discretion and handled the student's private problem without telling the class.",
"congeniality":"His warmth and congeniality made new coworkers feel comfortable around him immediately.",
"bravado":"His boast that he feared nobody was mostly bravado hiding his real nervousness.",
"enervating":"Working twelve hours in extreme heat was enervating and left everyone exhausted.",
"jarring":"The sudden scream was jarring, breaking the peaceful silence and startling everyone.",
"impregnable":"The fortress seemed impregnable because its thick walls and guards made entry nearly impossible.",
"precocious":"The precocious child was reading adult novels at only six years old.",
"diminutive":"The diminutive dog was so small that it could fit inside a large handbag.",
"superficial":"Their friendship was superficial because they chatted often but never shared anything personal.",
"tedious":"Entering hundreds of numbers by hand was tedious and painfully repetitive.",
"intrepid":"The intrepid explorer crossed the dangerous desert alone without turning back.",
"proclaimed":"The king proclaimed a national holiday, officially announcing it to the entire country.",
"quenched":"A cold drink quenched her thirst after the long run.",
"incarcerated":"He was incarcerated for ten years and spent that entire period in prison.",
"synthesized":"The chemical was synthesized in a laboratory rather than taken from a natural source.",
"discord":"There was constant discord between the two leaders because they disagreed on nearly everything.",
"heresy":"His religious ideas were considered heresy because they directly contradicted official church teachings.",
"credence":"The new evidence gave credence to her story and made people more likely to believe it.",
"germination":"Warm soil and water encouraged germination, and tiny shoots soon emerged from the seeds.",
"deferentially":"He spoke deferentially to the judge, showing clear respect in both tone and manner.",
"sequentially":"The instructions must be followed sequentially, completing step one before step two.",
"slenderly":"The tower rose slenderly above the village, looking tall and unusually thin.",
"discreetly":"She discreetly handed him the note under the table so nobody else would notice.",
"liaison":"She acts as a liaison between the school and parents, passing information between both sides.",
"entreaty":"His desperate entreaty for help sounded like a heartfelt plea.",
"levity":"A little levity helped everyone relax when he made a gentle joke during the tense meeting.",
"consignment":"The store received a consignment of fifty new laptops from its supplier that morning.",
"buttressing":"The extra beams were buttressing the roof and preventing it from collapsing.",
"assassination":"The president's assassination shocked the nation after he was deliberately killed by an attacker.",
"digression":"His long story about college was a digression that took the conversation away from the main topic.",
"coup":"The military coup removed the elected government and seized control of the country.",
"spurious":"The website made spurious claims with no reliable evidence to support them.",
"ailing":"The ailing company was losing money and struggling to stay in business.",
"overt":"His overt anger was obvious because he shouted and slammed the door.",
"magnanimous":"She was magnanimous in victory, praising her defeated opponent instead of insulting him.",
"jilted":"He felt humiliated after being jilted when his fiancée suddenly ended their engagement.",
"duped":"She was duped into buying a fake watch because the seller convinced her it was genuine.",
"slanted":"The article was slanted in favor of one candidate and ignored opposing views.",
"scampered":"The frightened rabbit scampered across the field in quick little steps.",
"scrawl":"He had to scrawl a quick note because he was already late for the train.",
"percolate":"Ideas began to percolate through the team, slowly spreading from one person to another.",
"pawn":"He decided to pawn his watch to get cash, hoping to buy it back later.",
"sully":"One dishonest act can sully a good reputation that took years to build.",
"pony up":"Everyone had to pony up twenty dollars to cover the unexpectedly large bill.",
"buckle down":"With exams approaching, she decided to buckle down and study seriously every evening.",
"foul up":"One wrong number can foul up the entire calculation and produce the wrong result.",
"cast down":"The rejection letter cast down his spirits and left him deeply discouraged.",
"breeze in":"She breezed in five minutes late as if nothing unusual had happened.",
"branch off":"A narrow path will branch off from the main road near the old bridge.",
"crack down":"Police began to crack down on illegal parking by issuing many more fines.",
"lop off":"The gardener had to lop off the damaged branch with a saw.",
"dwell on":"Try not to dwell on one mistake for hours; learn from it and move on.",
"reel off":"He could reel off all fifty state capitals from memory without pausing.",
"rustle up":"We had unexpected guests, so I tried to rustle up a quick dinner from leftovers.",
"haul off":"Workers came to haul off the broken furniture and take it away.",
"fritter away":"He tends to fritter away his allowance on snacks and small purchases.",
"rip off":"That shop tried to rip off tourists by charging ten times the normal price.",
"sound off":"Several residents began to sound off at the meeting, loudly expressing their complaints.",
"crop up":"Unexpected problems often crop up during large projects, even with careful planning.",
"callousness":"His callousness shocked everyone when he laughed at someone else's suffering.",
"impudence":"The student's impudence was obvious when he rudely mocked the teacher to her face.",
"treachery":"The general's treachery was revealed when he secretly helped the enemy.",
"benevolence":"Her benevolence was shown by years of generous donations to people in need.",
"straddles":"The town straddles the border, with one half in each country.",
"abates":"The storm usually abates by morning, becoming much weaker overnight.",
"coddles":"He coddles his son by solving every problem for him instead of letting him struggle.",
"recedes":"At low tide, the sea recedes and exposes a wide stretch of sand.",
"fortuitously":"Fortuitously, a taxi appeared just as we realized we were going to miss the train.",
"profusely":"She apologized profusely, saying sorry again and again for the mistake.",
"blatantly":"He blatantly cheated by looking directly at another student's answers.",
"dubiously":"She looked dubiously at the cheap medicine, clearly unsure whether she could trust it.",
"deliberation":"After careful deliberation for several hours, the committee finally reached a decision.",
"abolition":"The abolition of the old law meant it was completely removed from the legal system.",
"restitution":"The thief was ordered to pay restitution to the victims for the money he stole.",
"expulsion":"Repeated violence led to his expulsion, and he was permanently removed from the school.",
"denounced":"The mayor denounced the attack publicly and called it completely unacceptable.",
"banished":"The prince was banished from the kingdom and forbidden to return.",
"postulated":"The scientist postulated that an unseen planet might explain the strange movement.",
"mesmerized":"The audience was mesmerized by the dancer and watched her without looking away.",
"devoured":"The hungry child devoured the sandwich in less than a minute.",
"reviled":"The corrupt ruler was reviled by citizens who hated his cruelty.",
"ruffled":"The rude comment ruffled her and made her visibly annoyed.",
"deranged":"The attacker appeared deranged, shouting wildly and behaving without any sense of reality.",
"transcend":"Great music can transcend language barriers and move people who speak different languages.",
"procrastinate":"If you procrastinate until the night before, you may not finish the assignment on time.",
"evangelize":"He loves to evangelize about the new software, enthusiastically telling everyone to try it.",
"elucidate":"The diagram helped elucidate the process by making each step easier to understand.",
"boon":"The new train line was a boon to commuters because it cut travel time in half.",
"prose":"The novel is written in prose rather than poetry or verse.",
"tremor":"A small tremor shook the windows for a few seconds but caused no serious damage.",
"dent":"The falling bicycle left a dent in the car door, bending the metal inward.",
"viable":"The plan is financially viable because the company can actually afford to carry it out.",
"jammed":"The subway was jammed with passengers, leaving barely enough room to stand.",
"reticent":"He was reticent during the meeting and spoke only when directly asked.",
"slick":"The salesperson gave a slick presentation that sounded polished and highly professional.",
"exude":"Freshly baked bread can exude a warm aroma that fills the entire room.",
"deviate":"Pilots should not deviate from the approved route unless safety requires it.",
"crucify":"The press will crucify the politician if they discover he knowingly lied to voters.",
"agonize":"She tends to agonize over small decisions, worrying for hours about what to choose.",
"petrified":"He was petrified when the huge dog charged toward him and could not move.",
"rectified":"The billing error was rectified after the company corrected the amount on the invoice.",
"dignified":"She remained dignified during the argument, speaking calmly and refusing to insult anyone.",
"gratified":"He felt gratified when his students thanked him for helping them succeed.",
"lavish":"They held a lavish wedding with expensive food, flowers, and hundreds of guests.",
"impromptu":"We had an impromptu meeting in the hallway with no preparation or schedule.",
"vigilant":"Security guards must remain vigilant and watch carefully for anything suspicious.",
"endemic":"Malaria is endemic in some tropical regions, where it occurs regularly over many years.",
"gentry":"The local gentry owned large estates and belonged to the wealthy landowning class.",
"squad":"A small police squad was sent to search the building together.",
"parchment":"The ancient message was written on parchment made from treated animal skin.",
"rift":"A serious rift developed between the brothers after years of unresolved arguments.",
"sluggish":"After staying up all night, he felt sluggish and moved much more slowly than usual.",
"adroit":"Her adroit handling of the difficult customer quickly turned an argument into a calm discussion.",
"cranky":"The tired toddler became cranky and started complaining about everything.",
"distasteful":"He found the cruel joke distasteful and refused to laugh.",
"corpulent":"The corpulent man had a very large, heavy body.",
"meticulous":"She is meticulous about her notes, checking every date, spelling, and detail twice.",
"capricious":"The capricious boss changed the rules without warning whenever his mood changed."
});